apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-lflx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-lflx
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-lflx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-lflx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-lflx
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/release-e2e-deploy-tenant/appstudio/dc-metro-map-lflx@sha256:6120c694d5919098bdb4b6f618351326d665f3a3272904f0b035227e1a2bc503
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
